# Generated by Django 2.1.5 on 2019-02-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='desciption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gallery',
            name='index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
